package com.template.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.version
     *
     * @mbggenerated
     */
    private Long version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_name
     *
     * @mbggenerated
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_type
     *
     * @mbggenerated
     */
    private String companyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.role_id
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sort_one
     *
     * @mbggenerated
     */
    private String sortOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sort_three
     *
     * @mbggenerated
     */
    private String sortThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.sort_two
     *
     * @mbggenerated
     */
    private String sortTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.changwulishidanwei
     *
     * @mbggenerated
     */
    private String changwulishidanwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.fuhuizhangdanwei
     *
     * @mbggenerated
     */
    private String fuhuizhangdanwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lishidanwei
     *
     * @mbggenerated
     */
    private String lishidanwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pingtai
     *
     * @mbggenerated
     */
    private String pingtai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.zhunhuiyuandanwei
     *
     * @mbggenerated
     */
    private String zhunhuiyuandanwei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.company_code
     *
     * @mbggenerated
     */
    private String companyCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.version
     *
     * @return the value of user.version
     *
     * @mbggenerated
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.version
     *
     * @param version the value for user.version
     *
     * @mbggenerated
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.account
     *
     * @return the value of user.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.account
     *
     * @param account the value for user.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_name
     *
     * @return the value of user.company_name
     *
     * @mbggenerated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_name
     *
     * @param companyName the value for user.company_name
     *
     * @mbggenerated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_type
     *
     * @return the value of user.company_type
     *
     * @mbggenerated
     */
    public String getCompanyType() {
        return companyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_type
     *
     * @param companyType the value for user.company_type
     *
     * @mbggenerated
     */
    public void setCompanyType(String companyType) {
        this.companyType = companyType == null ? null : companyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.role_id
     *
     * @return the value of user.role_id
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.role_id
     *
     * @param roleId the value for user.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sort_one
     *
     * @return the value of user.sort_one
     *
     * @mbggenerated
     */
    public String getSortOne() {
        return sortOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sort_one
     *
     * @param sortOne the value for user.sort_one
     *
     * @mbggenerated
     */
    public void setSortOne(String sortOne) {
        this.sortOne = sortOne == null ? null : sortOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sort_three
     *
     * @return the value of user.sort_three
     *
     * @mbggenerated
     */
    public String getSortThree() {
        return sortThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sort_three
     *
     * @param sortThree the value for user.sort_three
     *
     * @mbggenerated
     */
    public void setSortThree(String sortThree) {
        this.sortThree = sortThree == null ? null : sortThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.sort_two
     *
     * @return the value of user.sort_two
     *
     * @mbggenerated
     */
    public String getSortTwo() {
        return sortTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.sort_two
     *
     * @param sortTwo the value for user.sort_two
     *
     * @mbggenerated
     */
    public void setSortTwo(String sortTwo) {
        this.sortTwo = sortTwo == null ? null : sortTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.changwulishidanwei
     *
     * @return the value of user.changwulishidanwei
     *
     * @mbggenerated
     */
    public String getChangwulishidanwei() {
        return changwulishidanwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.changwulishidanwei
     *
     * @param changwulishidanwei the value for user.changwulishidanwei
     *
     * @mbggenerated
     */
    public void setChangwulishidanwei(String changwulishidanwei) {
        this.changwulishidanwei = changwulishidanwei == null ? null : changwulishidanwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.fuhuizhangdanwei
     *
     * @return the value of user.fuhuizhangdanwei
     *
     * @mbggenerated
     */
    public String getFuhuizhangdanwei() {
        return fuhuizhangdanwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.fuhuizhangdanwei
     *
     * @param fuhuizhangdanwei the value for user.fuhuizhangdanwei
     *
     * @mbggenerated
     */
    public void setFuhuizhangdanwei(String fuhuizhangdanwei) {
        this.fuhuizhangdanwei = fuhuizhangdanwei == null ? null : fuhuizhangdanwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lishidanwei
     *
     * @return the value of user.lishidanwei
     *
     * @mbggenerated
     */
    public String getLishidanwei() {
        return lishidanwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lishidanwei
     *
     * @param lishidanwei the value for user.lishidanwei
     *
     * @mbggenerated
     */
    public void setLishidanwei(String lishidanwei) {
        this.lishidanwei = lishidanwei == null ? null : lishidanwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pingtai
     *
     * @return the value of user.pingtai
     *
     * @mbggenerated
     */
    public String getPingtai() {
        return pingtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pingtai
     *
     * @param pingtai the value for user.pingtai
     *
     * @mbggenerated
     */
    public void setPingtai(String pingtai) {
        this.pingtai = pingtai == null ? null : pingtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.zhunhuiyuandanwei
     *
     * @return the value of user.zhunhuiyuandanwei
     *
     * @mbggenerated
     */
    public String getZhunhuiyuandanwei() {
        return zhunhuiyuandanwei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.zhunhuiyuandanwei
     *
     * @param zhunhuiyuandanwei the value for user.zhunhuiyuandanwei
     *
     * @mbggenerated
     */
    public void setZhunhuiyuandanwei(String zhunhuiyuandanwei) {
        this.zhunhuiyuandanwei = zhunhuiyuandanwei == null ? null : zhunhuiyuandanwei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.company_code
     *
     * @return the value of user.company_code
     *
     * @mbggenerated
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.company_code
     *
     * @param companyCode the value for user.company_code
     *
     * @mbggenerated
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode == null ? null : companyCode.trim();
    }
}